// 150+ Digital Services seed catalog
const S = (id, name, category, price, time, popular = false, govt = false, docs = [], desc = '') => ({
  id, name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
  category, price, time, popular, govt,
  documents: docs.length ? docs : ['Aadhaar Card', 'PAN Card', 'Passport size photo'],
  description: desc || `Apply for ${name} online through our verified service portal. Fast processing, secure document handling, and dedicated support throughout the application journey.`,
});

export const CATEGORIES = [
  { id: 'govt', name: 'Government Documents', icon: 'FileText', color: 'from-purple-500 to-indigo-500' },
  { id: 'utility', name: 'Utility Bills', icon: 'Zap', color: 'from-amber-500 to-orange-500' },
  { id: 'banking', name: 'Banking & Finance', icon: 'Landmark', color: 'from-emerald-500 to-teal-500' },
  { id: 'insurance', name: 'Insurance', icon: 'Shield', color: 'from-blue-500 to-cyan-500' },
  { id: 'tax', name: 'Tax & Compliance', icon: 'Receipt', color: 'from-rose-500 to-pink-500' },
  { id: 'travel', name: 'Travel & Booking', icon: 'Plane', color: 'from-violet-500 to-fuchsia-500' },
  { id: 'recharge', name: 'Recharge & Bills', icon: 'Smartphone', color: 'from-lime-500 to-green-500' },
  { id: 'welfare', name: 'Welfare Schemes', icon: 'HeartHandshake', color: 'from-yellow-500 to-amber-500' },
  { id: 'education', name: 'Education', icon: 'GraduationCap', color: 'from-sky-500 to-blue-500' },
  { id: 'health', name: 'Health Services', icon: 'Stethoscope', color: 'from-red-500 to-rose-500' },
];

export const SERVICES = [
  // Government Documents (govt)
  S(1, 'PAN Card New', 'govt', 199, '7-10 days', true, true, ['Aadhaar', 'Photo', 'Signature']),
  S(2, 'PAN Card Correction', 'govt', 149, '5-7 days', true, true),
  S(3, 'Aadhaar Update', 'govt', 99, '3-5 days', true, true, ['Aadhaar', 'Proof of update']),
  S(4, 'Aadhaar Print PVC', 'govt', 79, '5-7 days', true, true),
  S(5, 'Voter ID New', 'govt', 0, '15-20 days', true, true, ['Aadhaar', 'Address proof']),
  S(6, 'Voter ID Correction', 'govt', 0, '10-15 days', false, true),
  S(7, 'Passport Fresh', 'govt', 1499, '30-45 days', true, true, ['Aadhaar', 'Birth cert', 'Address proof']),
  S(8, 'Passport Renewal', 'govt', 1499, '20-30 days', true, true),
  S(9, 'Tatkal Passport', 'govt', 3499, '7-14 days', false, true),
  S(10, 'Driving Licence Learner', 'govt', 499, '7-14 days', true, true, ['Aadhaar', 'Address proof', 'Age proof']),
  S(11, 'Driving Licence Permanent', 'govt', 999, '15-30 days', true, true),
  S(12, 'DL Renewal', 'govt', 599, '7-14 days', false, true),
  S(13, 'Birth Certificate', 'govt', 199, '7-15 days', true, true, ['Hospital discharge', 'Parents Aadhaar']),
  S(14, 'Death Certificate', 'govt', 199, '7-15 days', false, true),
  S(15, 'Income Certificate', 'govt', 299, '7-10 days', true, true, ['Aadhaar', 'Income proof']),
  S(16, 'Caste Certificate', 'govt', 299, '10-15 days', true, true, ['Aadhaar', 'Caste proof']),
  S(17, 'Domicile Certificate', 'govt', 299, '10-15 days', true, true, ['Aadhaar', 'Address proof']),
  S(18, 'EWS Certificate', 'govt', 299, '7-14 days', false, true),
  S(19, 'Marriage Certificate', 'govt', 499, '15-30 days', false, true, ['Marriage proof', 'Witness Aadhaar']),
  S(20, 'Ration Card New', 'govt', 199, '15-30 days', false, true),
  S(21, 'Ration Card Update', 'govt', 149, '7-14 days', false, true),
  S(22, 'Senior Citizen Card', 'govt', 99, '5-7 days', false, true),
  S(23, 'Disability Certificate', 'govt', 199, '15-30 days', false, true),
  S(24, 'Police Verification', 'govt', 399, '15-30 days', false, true),
  S(25, 'Character Certificate', 'govt', 299, '7-14 days', false, true),
  S(26, 'NOC Certificate', 'govt', 299, '7-14 days', false, true),
  S(27, 'Land Records', 'govt', 199, '5-7 days', false, true),
  S(28, 'Property Tax', 'govt', 99, '1-3 days', false, true),
  S(29, 'Encumbrance Certificate', 'govt', 399, '7-14 days', false, true),
  S(30, 'Khata Certificate', 'govt', 299, '7-14 days', false, true),
  S(31, 'DigiLocker Setup', 'govt', 0, 'Instant', false, true),
  S(32, 'eShram Card', 'govt', 49, '3-5 days', true, true),
  S(33, 'ABHA Health ID', 'govt', 0, 'Instant', true, true),
  S(34, 'Udyam Registration', 'govt', 499, '3-5 days', true, true),

  // Utility Bills (utility)
  S(35, 'Electricity Bill Payment', 'utility', 9, 'Instant', true, false, ['Bill number']),
  S(36, 'New Electricity Connection', 'utility', 999, '15-30 days', false, false),
  S(37, 'Water Bill Payment', 'utility', 9, 'Instant', true, false),
  S(38, 'New Water Connection', 'utility', 1499, '20-30 days', false, false),
  S(39, 'Gas Booking (LPG)', 'utility', 19, 'Instant', true, false),
  S(40, 'PNG New Connection', 'utility', 1999, '15-30 days', false, false),
  S(41, 'Broadband Bill', 'utility', 9, 'Instant', false, false),
  S(42, 'Landline Bill', 'utility', 9, 'Instant', false, false),
  S(43, 'DTH Recharge', 'utility', 9, 'Instant', true, false),
  S(44, 'Postpaid Mobile Bill', 'utility', 9, 'Instant', true, false),
  S(45, 'Cable TV Bill', 'utility', 9, 'Instant', false, false),
  S(46, 'Municipal Tax', 'utility', 19, '1-3 days', false, false),

  // Banking & Finance
  S(47, 'SBI Account Opening', 'banking', 299, '5-7 days', true, false, ['Aadhaar', 'PAN', 'Photo']),
  S(48, 'IPPB Account Opening', 'banking', 199, '3-5 days', true, false),
  S(49, 'Jan Dhan Account', 'banking', 99, '3-5 days', true, false),
  S(50, 'Bank KYC Update', 'banking', 99, '1-3 days', true, false),
  S(51, 'Cheque Book Request', 'banking', 49, '7-10 days', false, false),
  S(52, 'Personal Loan Application', 'banking', 999, '7-15 days', false, false),
  S(53, 'Home Loan Application', 'banking', 1999, '15-30 days', false, false),
  S(54, 'Business Loan', 'banking', 1499, '15-30 days', false, false),
  S(55, 'Mudra Loan', 'banking', 499, '10-20 days', true, false),
  S(56, 'Credit Card Application', 'banking', 199, '7-15 days', false, false),
  S(57, 'Fixed Deposit Opening', 'banking', 99, '1-3 days', false, false),
  S(58, 'RD Account', 'banking', 99, '1-3 days', false, false),
  S(59, 'PPF Account Opening', 'banking', 199, '3-5 days', false, false),
  S(60, 'NPS Registration', 'banking', 299, '5-7 days', false, false),
  S(61, 'SSY Sukanya Samriddhi', 'banking', 199, '3-5 days', true, false),
  S(62, 'Sovereign Gold Bond', 'banking', 99, '7-10 days', false, false),
  S(63, 'Demat Account Opening', 'banking', 299, '3-5 days', false, false),

  // Insurance
  S(64, 'LIC Premium Payment', 'insurance', 9, 'Instant', true, false),
  S(65, 'LIC New Policy', 'insurance', 999, '7-15 days', true, false),
  S(66, 'Health Insurance', 'insurance', 599, '3-7 days', true, false),
  S(67, 'Vehicle Insurance', 'insurance', 299, '1-3 days', true, false),
  S(68, 'Two Wheeler Insurance', 'insurance', 199, '1-3 days', true, false),
  S(69, 'Term Life Insurance', 'insurance', 799, '7-15 days', false, false),
  S(70, 'Travel Insurance', 'insurance', 199, '1 day', false, false),
  S(71, 'Crop Insurance (PMFBY)', 'insurance', 99, '7-15 days', false, false),
  S(72, 'PMJJBY Enrollment', 'insurance', 99, '3-5 days', true, false),
  S(73, 'PMSBY Enrollment', 'insurance', 99, '3-5 days', true, false),
  S(74, 'Atal Pension Yojana', 'insurance', 199, '5-7 days', true, false),

  // Tax & Compliance
  S(75, 'GST Registration', 'tax', 999, '5-10 days', true, true, ['PAN', 'Aadhaar', 'Business proof']),
  S(76, 'GST Return Filing', 'tax', 499, '1-3 days', true, true),
  S(77, 'GST Cancellation', 'tax', 599, '7-15 days', false, true),
  S(78, 'Income Tax Return (ITR-1)', 'tax', 499, '1-3 days', true, true),
  S(79, 'ITR-2 Filing', 'tax', 799, '2-5 days', false, true),
  S(80, 'ITR-4 Filing', 'tax', 699, '2-5 days', false, true),
  S(81, 'TDS Return', 'tax', 599, '2-5 days', false, true),
  S(82, 'PAN-Aadhaar Linking', 'tax', 99, '1-3 days', true, true),
  S(83, 'Digital Signature Class 3', 'tax', 1499, '2-5 days', true, true),
  S(84, 'MSME Registration', 'tax', 499, '3-5 days', true, true),
  S(85, 'Trademark Registration', 'tax', 4999, '15-30 days', false, true),
  S(86, 'Company Registration', 'tax', 6999, '15-30 days', false, true),
  S(87, 'FSSAI Registration', 'tax', 999, '7-15 days', false, true),
  S(88, 'Shop Act Licence', 'tax', 499, '5-10 days', false, true),
  S(89, 'Import Export Code (IEC)', 'tax', 999, '5-10 days', false, true),
  S(90, 'Form 16 Generation', 'tax', 199, '1-2 days', false, true),

  // Travel & Booking
  S(91, 'IRCTC Train Booking', 'travel', 29, 'Instant', true, false),
  S(92, 'IRCTC ID Creation', 'travel', 49, '1 day', true, false),
  S(93, 'Tatkal Train Booking', 'travel', 49, 'Instant', true, false),
  S(94, 'Flight Booking', 'travel', 99, 'Instant', true, false),
  S(95, 'Bus Booking', 'travel', 29, 'Instant', true, false),
  S(96, 'Hotel Booking', 'travel', 49, 'Instant', false, false),
  S(97, 'FASTag New', 'travel', 499, '3-5 days', true, true),
  S(98, 'FASTag Recharge', 'travel', 9, 'Instant', true, true),
  S(99, 'Vehicle RC Transfer', 'travel', 999, '15-30 days', false, true),
  S(100, 'Vehicle Fitness Certificate', 'travel', 499, '7-14 days', false, true),
  S(101, 'Vehicle Pollution Cert', 'travel', 99, 'Instant', false, true),
  S(102, 'International Driving Permit', 'travel', 1299, '7-14 days', false, true),
  S(103, 'Visa Assistance', 'travel', 1999, '7-30 days', false, false),
  S(104, 'Passport Appointment', 'travel', 199, '1 day', false, true),

  // Recharge & Bills
  S(105, 'Mobile Recharge Prepaid', 'recharge', 9, 'Instant', true, false),
  S(106, 'Jio Recharge', 'recharge', 9, 'Instant', true, false),
  S(107, 'Airtel Recharge', 'recharge', 9, 'Instant', true, false),
  S(108, 'VI Recharge', 'recharge', 9, 'Instant', false, false),
  S(109, 'BSNL Recharge', 'recharge', 9, 'Instant', false, false),
  S(110, 'Tata Sky Recharge', 'recharge', 9, 'Instant', false, false),
  S(111, 'Dish TV Recharge', 'recharge', 9, 'Instant', false, false),
  S(112, 'Airtel DTH', 'recharge', 9, 'Instant', false, false),
  S(113, 'Sun Direct Recharge', 'recharge', 9, 'Instant', false, false),
  S(114, 'D2H Recharge', 'recharge', 9, 'Instant', false, false),
  S(115, 'BBPS Bill Payment', 'recharge', 9, 'Instant', true, false),
  S(116, 'Money Transfer (DMT)', 'recharge', 19, 'Instant', true, false),
  S(117, 'AEPS Cash Withdrawal', 'recharge', 9, 'Instant', true, false),
  S(118, 'Courier Booking (DTDC)', 'recharge', 49, '1-2 days', false, false),
  S(119, 'Bluedart Booking', 'recharge', 79, '1-2 days', false, false),
  S(120, 'India Post Speed Post', 'recharge', 39, '1-2 days', false, false),

  // Welfare Schemes
  S(121, 'PM Kisan Registration', 'welfare', 99, '7-15 days', true, true),
  S(122, 'PM Kisan Status Check', 'welfare', 19, 'Instant', true, true),
  S(123, 'Ayushman Bharat Card', 'welfare', 49, '5-7 days', true, true),
  S(124, 'PMAY Application', 'welfare', 299, '15-30 days', true, true),
  S(125, 'Old Age Pension', 'welfare', 199, '15-30 days', true, true),
  S(126, 'Widow Pension', 'welfare', 199, '15-30 days', false, true),
  S(127, 'Disability Pension', 'welfare', 199, '15-30 days', false, true),
  S(128, 'NSAP Scheme', 'welfare', 99, '7-14 days', false, true),
  S(129, 'Labour Card', 'welfare', 99, '7-14 days', true, true),
  S(130, 'BOCW Registration', 'welfare', 149, '10-15 days', false, true),
  S(131, 'MGNREGA Job Card', 'welfare', 99, '7-14 days', true, true),
  S(132, 'Scholarship Application', 'welfare', 99, '15-30 days', true, true),
  S(133, 'Mid Day Meal Registration', 'welfare', 49, '7-14 days', false, true),
  S(134, 'Annapurna Yojana', 'welfare', 49, '7-14 days', false, true),

  // Education
  S(135, 'School Admission Form', 'education', 199, '1-3 days', false, false),
  S(136, 'College Admission Form', 'education', 299, '1-3 days', false, false),
  S(137, 'UPSC Application', 'education', 299, '1-3 days', false, true),
  S(138, 'SSC Application', 'education', 199, '1-3 days', true, true),
  S(139, 'Bank PO Application', 'education', 199, '1-3 days', false, true),
  S(140, 'Railway RRB Form', 'education', 199, '1-3 days', false, true),
  S(141, 'NEET Application', 'education', 299, '1-3 days', true, true),
  S(142, 'JEE Application', 'education', 299, '1-3 days', true, true),
  S(143, 'Mark Sheet Verification', 'education', 499, '7-15 days', false, true),
  S(144, 'Migration Certificate', 'education', 299, '7-14 days', false, true),

  // Health
  S(145, 'Doctor Online Consult', 'health', 299, 'Same day', true, false),
  S(146, 'Lab Test Booking', 'health', 99, '1-2 days', true, false),
  S(147, 'Health Checkup Package', 'health', 999, '1-2 days', false, false),
  S(148, 'Medicine Order', 'health', 49, '1-2 days', false, false),
  S(149, 'Mental Health Consult', 'health', 499, 'Same day', false, false),
  S(150, 'ABHA Health Card', 'health', 49, '1-2 days', true, true),
  S(151, 'Vaccination Appointment', 'health', 0, 'Same day', false, true),
  S(152, 'CoWIN Certificate', 'health', 19, 'Instant', false, true),
];

export const PARTNERS = [
  'CSC', 'UIDAI', 'DigiLocker', 'Protean', 'UTIITSL', 'Passport Seva', 'IRCTC', 'NPCI', 'BBPS',
  'LIC', 'SBI', 'IPPB', 'PM Kisan', 'Ayushman Bharat', 'GST', 'Income Tax',
  'National Insurance', 'New India Assurance', 'United India', 'Oriental Insurance'
];

export const TESTIMONIALS = [
  { name: 'Rajesh Kumar', role: 'Small Business Owner', text: 'Got my GST registration done in 3 days. Excellent service and constant updates.', rating: 5 },
  { name: 'Priya Sharma', role: 'Homemaker', text: 'Applied for Aadhaar update from home. Super smooth process — saved me a full day at the seva kendra.', rating: 5 },
  { name: 'Amit Patel', role: 'Freelancer', text: 'Filed my ITR in just 30 minutes. Team helped with deductions I didn\u2019t even know about.', rating: 5 },
  { name: 'Sneha Reddy', role: 'Student', text: 'Tatkal passport in 9 days! Best service for last-minute travel needs.', rating: 5 },
  { name: 'Vikram Singh', role: 'Farmer', text: 'PM Kisan registration was free and they followed up till the money came.', rating: 5 },
  { name: 'Anita Verma', role: 'Teacher', text: 'Driving Licence renewal was painless. No more standing in long queues.', rating: 5 },
];
